### PR TITLE
[Composer] Fix infinite retry for OpenCTI connection with configurable timeouts

### LINKED ISSUE #35: XTM Hub tries to connect to OpenCTI for some time, then get stuck and does not retry
## Description

XTM Hub tries to connect to OpenCTI for 3 minutes (or ~19 times), then stop retrying forever, and does not crash.

## Environment

1. OS (where XTM Composer runs): { e.g. Mac OS 10, Windows 10, Ubuntu 22.04, etc. }
2. XTM Composer version: { e.g. XTM Composer 0.1.0 }
3. Rust version: { e.g. 1.70.0 }
4. Orchestrator: { e.g. Docker, Kubernetes, Portainer }
5. OpenCTI version: { e.g. OpenCTI 6.0.0 }
6. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Stop OpenCTI
2. Start XTM Composer

## Expected Output

Infinite error logs until connection is successful. If not possible, just crash after sufficient retries.

## Actual Output

Some errors, then it stops retrying, but it's still not connected to OpenCTI. Restarting XTM Composer works.

```
{
  "timestamp": "2025-10-13T09:32:17.120477Z",
  "level": "ERROR",
  "fields": {
    "message": "Fail to fetch connectors",
    "error": "Error making HTTP request: error sending request for url (http://10.1.1.1/graphql)"
  },
  "target": "xtm_composer::api::opencti::connector::get_listing"
}
```

## Configuration

```yaml
# config/default.yaml or relevant configuration
```

## Logs

```
# Log output here
```

### PR DESCRIPTION
**Pull request by maelv-filigran**
### Proposed changes
This PR fixes the issue where XTM Hub stops retrying to connect to OpenCTI after ~3 minutes and gets stuck without crashing or retrying.

### Related issues
- Fixes #35
- OCTI #13033

**Changes implemented:**
1. **Infinite retry loop**: To continuously retry connection attempts when OpenCTI is unavailable
2. **Configurable HTTP timeouts**: Added `request_timeout` (default: 30s) and `connect_timeout` (default: 10s) parameters for both OpenCTI and OpenBAS
3. **Connection loss handling**: The ping loop now breaks back to the retry loop when connection is lost, enabling automatic reconnection
4. **Configuration support**: Timeouts are configurable via YAML config and environment variables (`OPENCTI__REQUEST_TIMEOUT`, `OPENCTI__CONNECT_TIMEOUT`, etc.)

**Behavior:**
- On startup: Continuously retries until OpenCTI is reachable
- During operation: If connection is lost, automatically breaks and retries
- HTTP requests timeout quickly (10s connect, 30s total) to avoid long hangs
- Error logs continue to be generated during connection attempts

### CODE REVIEW

File: src/api/opencti/mod.rs [hunk 1]
```diff
@@ -54,6 +60,8 @@ impl ApiOpenCTI {
     {
         use cynic::http::ReqwestExt;
         reqwest::Client::builder()
+            .timeout(Duration::from_secs(self.request_timeout))
```
Comment (richard-julien) [inline src/api/opencti/mod.rs]: Have you checked how we handle the error produce by this method if a timeout occured?
